name: Deploy to Production (Simulado)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Construir imagen Docker (simulado)
        run: |
          echo "Iniciando build de Docker..."
          docker build -t devops-prueba:latest .
          echo "Build finalizado correctamente."

      - name: Simular despliegue
        run: |
          echo "Despliegue SIMULADO ejecutado (sin SSH)."
          echo "Aquí iría el SSH real cuando tengamos servidor."
